version: '3.8'

services:
  mysql:
    build:
      context: mysql/
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      OPENMRS_DB_USER: ${OPENMRS_DB_USER:-openmrs-user}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
    healthcheck:
      test: mysql --user=$$OPENMRS_DB_USER --password=$$OPENMRS_DB_PASSWORD -e 'SHOW DATABASES;'
      timeout: 1s
    image: bahmni/mysql
    ports:
      - "3306:3306"
    restart: "always"
